version: '3.9'
services:
    the-secret-ingredient-frontend:
        image: senbonzakura/secretingredient:latest
        container_name: the-secret-ingredient-frontend
        ports:
            - '3000:3000'
        restart: unless-stopped
        networks:
            - the-secret-ingredient-frontend

networks:
    the-secret-ingredient-frontend:
        driver: bridge