version: '3.9'
services:
    the-secret-ingredient-backend:
        build:
            context: .
        container_name: the-secret-ingredient-backend
        restart: unless-stopped
        networks:
            - the-secret-ingredient-backend
        ports:
            - ${APP_PORT}:${APP_PORT}
        environment:
            - APP_PORT=${APP_PORT}
            - MONGODB_CONNECT_STRING=${MONGODB_CONNECT_STRING}
            - JWK=${JWK}

networks:
    the-secret-ingredient-backend:
        driver: bridge